# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html
namespace: dark-land
name: icx
version: 1.0
readme: README.md
authors:
  - dark-nico
description: Ansible Network Collection for Commscope ICX devices.
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - commscope
  - icx
  - ruckus
  - networking
dependencies:
  "ansible.netcommon": ">=1.0.0"
repository: https://github.com/dark-nico/RUCKUS_ICX_Ansible
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://www.commscope.com/
issues: https://github.com/dark-nico/RUCKUS_ICX_Ansible/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
